import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import AudioPlayer from "~/components/AudioPlayer";
import Game from "~/components/Game";
import Navbar from "~/components/Navbar";
import { PlayerStats } from "~/server/api/routers/game";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main h-screen w-screen bg-[url('/game-bg.jpg')] bg-cover">
        <Navbar />
        <AudioPlayer />
        <div>
          
            <>
              <Game />
            </>
        </div>
      </main>
    </>
  );
};

export default Home;
